name: EventSystem
version: 'DEV-0.0.2'
main: sk.adr3ez.eventsystem.Main
api-version: 1.17
softdepend: [ PlaceholderAPI ]
authors: [ Adr3ez_ ]
description: Event system plugin.
commands:
  event:
    description: Main command for everything
    aliases:
      - es
      - e
  eventeditor:
    description: Edit everything you need
    aliases:
      - ee